server:
  port: 8080

logging:
  level:
    org.springframework: ERROR
    org.springframework.web: DEBUG

# spring mvc
spring.thymeleaf.cache: false
spring.thymeleaf.check-template: true
spring.thymeleaf.check-template-location: true
spring.thymeleaf.content-type: text/html
spring.thymeleaf.enabled: true
spring.thymeleaf.encoding: UTF-8
spring.thymeleaf.prefix: /WEB-INF/views/
spring.thymeleaf.suffix: .html

# jpa
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/deepwork
    username: Developer
    password:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL9Dialect
        show_sql: false
        format_sql: false
        ejb.naming_strategy: org.hibernate.cfg.ImprovedNamingStrategy
        hbm2ddl:
          auto: validate
